services:
  # app:
  
  #   image: 'docker-spring-boot-postgres:latest'
  #   build:
  #     context: ./nvtbackend
  #   volumes:
  #     - ./src:/app/src  # Maps local src folder to container's src folder
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgresdb
  #     SPRING_DATASOURCE_USERNAME: nvt
  #     SPRING_DATASOURCE_PASSWORD: 123
  #   depends_on:
  #     - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: nvt
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgresdb
    ports:
      - "5432:5432"

  influxdb:
      image: influxdb:2.7
      container_name: influxdb
      environment:
        INFLUXDB_ADMIN_USER: nvt
        INFLUXDB_ADMIN_PASSWORD: 123
        INFLUXDB_DB: my_database
      # volumes:
      #   - influxdb-data:/var/lib/influxdb2
      ports:
        - "8086:8086"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Port for RabbitMQ messaging
      - "15672:15672" # Port for RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: nvt
      RABBITMQ_DEFAULT_PASS: 123

# volumes:
#   influxdb-data: