services:
  # app:
  
  #   image: 'docker-spring-boot-postgres:latest'
  #   build:
  #     context: ./nvtbackend
  #   volumes:
  #     - ./src:/app/src  # Maps local src folder to container's src folder
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgresdb
  #     SPRING_DATASOURCE_USERNAME: nvt
  #     SPRING_DATASOURCE_PASSWORD: 123
  #   depends_on:
  #     - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: nvt
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgresdb
    ports:
      - "5432:5432"
    volumes:
    - ./nvtbackend/data:/docker-entrypoint-initdb.d:ro

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    environment:
      INFLUXDB_ADMIN_USER: nvt
      INFLUXDB_ADMIN_PASSWORD: 123
      INFLUXDB_DB: my_database
    ports:
      - "8086:8086"
    volumes:
      - ./nvtbackend/data/influxdb/electricity_compact.lp:/tmp/electricity_compact.lp:ro

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Messaging port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: nvt
      RABBITMQ_DEFAULT_PASS: 123

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # Expose Nginx on port 80
    volumes:
      # Mount Nginx configuration file
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

      # Mount the 'files' directory to serve user-uploaded content
      - ./nvtbackend/files:/files:ro

    extra_hosts:
      - "host.docker.internal:host-gateway"

    depends_on:
      - db
      - influxdb
      - rabbitmq
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.http.ssl.enabled=false
      - xpack.security.enabled=false  
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: